### ISSUE TITLE
Ненужные переменные

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#1]
Копировать значения констант в переменные не нужно
https://github.com/Alfatyhin/loftshool/blob/4001456dbf666983959b8ab909eed550c87e61e4/tasks/week_1/task_1.php#L23-L25

Ты можешь использовать значения констант в выражениях
```
$imagePaints = IMAGE - IMAGE_FELT - IMAGE_PEN;
```

Важно помнить, что присвоить значение константе ты не можешь. Но использовать их значения можно.

**Comment by Alfatyhin** [comment]
исправил
