### ISSUE TITLE
Использование библиотечных функций

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#10]
https://github.com/Alfatyhin/loftshool/blob/24b9680b1f36251201d228501fc24cf8ec3edce8/tasks/week_2/src/functions.php#L13-L21

Старайся использовать библиотечные функции.
Например, для подсчета суммы массива - array_sum()
Для получения массива имен - array_map()
Дляпосчета элементов массива - count()

**Comment by Alfatyhin** [comment]
изменил правда не понял как посчитать сумму поля age в многомерном массиве и сделал тоже через arry_map
