### ISSUE TITLE
Привести к psr-2

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#11]
Вынести настройки подключения к бд в отдельный фаил (username, password, db, host)
https://github.com/Alfatyhin/loftshool/blob/871e8ffb495fbe9af6b642dfa3ead66b0b21052e/response_form.php#L25

**Comment by Alfatyhin** [comment]
> Вынести настройки подключения к бд в отдельный фаил (username, password, db, host)
> https://github.com/Alfatyhin/loftshool/blob/871e8ffb495fbe9af6b642dfa3ead66b0b21052e/response_form.php#L25

сделал
