### ISSUE TITLE
Улучшение логики

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#12]
Верно подметил в комете, что должна быть возможность удалить
доп услуги. При текущей реализации это сделать нельзя.

https://github.com/Alfatyhin/loftshool/blob/53d9df5f301d6faa89aa7eb2d274f66507cf0e32/tasks/week_2/src/TarifAbstract.php#L39-L47

Но если ты создашь свойство классе TarifAbstract - массив сервисов.
И будешь добавлять в него сервисы в методе addServices,
тогда у тебя будет список сервисов добавленных к тарифу.
А применять логику доп сервисов будешь в методе count().

**Comment by Alfatyhin** [comment]
> Верно подметил в комете, что должна быть возможность удалить
> доп услуги. При текущей реализации это сделать нельзя.
> 
> https://github.com/Alfatyhin/loftshool/blob/53d9df5f301d6faa89aa7eb2d274f66507cf0e32/tasks/week_2/src/TarifAbstract.php#L39-L47
> 
> Но если ты создашь свойство классе TarifAbstract - массив сервисов.
> И будешь добавлять в него сервисы в методе addServices,
> тогда у тебя будет список сервисов добавленных к тарифу.
> А применять логику доп сервисов будешь в методе count().

сделал правда метод count считает тариф а доп услуги обрабатывает getCount так как один из тарифов переопределяет метод count и чтоб не делать в нем обработку доп услуг сделал так
