### ISSUE TITLE
Разбить регистрацию на 2 роута

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#13]
https://github.com/Alfatyhin/loftshool/blob/3ed894319edd7309b4ac1e24a5ed55588dc754da/tasks/week_3/app/Controller/User.php#L36-L80

Предлагаю разбить на два роута:
1. Только показывает форму
2. Отвечает за обработку формы (если она передана). Если нет, то редиректит на 1ый

**Comment by Alfatyhin** [comment]
> Предлагаю разбить на два роута:

Сделал
