### ISSUE TITLE
Генерация уникального имени для файла

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#16]
https://github.com/Alfatyhin/loftshool/blob/3ed894319edd7309b4ac1e24a5ed55588dc754da/tasks/week_3/app/Controller/Blog.php#L37

Такой алгоритм достаточно слабый, так как не гарантирует уникальность имени файла.

Предлагаю поставить через комплзер эту либу
https://github.com/ramsey/uuid

И генерировать имя файла через неё
```
$name = Uuid::uuid4();
```

**Comment by Alfatyhin** [comment]
> https://github.com/Alfatyhin/loftshool/blob/3ed894319edd7309b4ac1e24a5ed55588dc754da/tasks/week_3/app/Controller/Blog.php#L37
> 

переделал
