### ISSUE TITLE
Порядок условий

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#2]
В целом все верно.
Единственное, я бы поменял порядок условий для 
улучшения читаемости кода
https://github.com/Alfatyhin/loftshool/blob/4001456dbf666983959b8ab909eed550c87e61e4/tasks/week_1/task_1.php#L38-L51

```
if ($age >= 1 && $age <= 17) {
...
} elseif ($age >= 18 && $age <= 65) { 
...
} elseif ($age > 65) {
...
```
Так код будет более читаемым и понятным.

**Comment by Alfatyhin** [comment]
да, делал в порядке постановки задачи, но так действительно лучше. поправил
