### ISSUE TITLE
Устранение дублирования

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#5]
https://github.com/Alfatyhin/loftshool/blob/54183ad7e815ab5601f398e83a879fe927081824/tasks/week_1/task_1.php#L109-L149

1. Имена переменных
Старайся давать осмысленные имена переменным. Например цикл
```
 for ($b = 1; $b <= 10; $b++){ 
     echo "<th> $b </th>"; 
 } 
 ```
 Лучше переименовать в 
 ```
for ($header = 1; $header <= 10; $header++){
    echo "<th> $header </th>";
}
 ```
Так же и с остальными:
$a лучше переименовать в $line, а $b - в $column

2. Устранение дублирования:
В данной реализации присутствует дублирование логики.
Мы два раза вычисляем четность
```
if ($b & 1) { 
```
Оптимальным будет ввести две переменных:
$isEvenLine и $isEvenColumn и сохранить в них значение четности строки/столбца.

Тогда при выводе мы просто сверим эти переменные с условиями:
```
        if ($isEvenLine && $isEvenColumn) {
        .....
        } elseif (!$isEvenLine && !$isEvenColumn) {
        .....
        } else {
        .....
        }
```

**Comment by Alfatyhin** [comment]
исправил
