### ISSUE TITLE
Неверная логика функции

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#6]
Немного неправильно работает функция
https://github.com/Alfatyhin/loftshool/blob/76ade06ffcd55ee034328a217defd82c3930c5fa/tasks/week_1/src/functions.php#L3-L17

Из задания.
```
Функция должна принимать массив строк и выводить каждую строку в отдельном параграфе (тег <p>)
```
То есть внутри функции должен быть вывод (если второй параметр `false`)

**Comment by Alfatyhin** [comment]
Так она так и делает вроде. При значении rtue выводит в объединенной строке только я добавил чтоб строка была в параграфе. При false или отсутствии каждая в отдельном параграфе
