### ISSUE TITLE
Добавить валидацию параметров 

### ISSUE THREAD

**Issue by nejtr0n** [Alfatyhin/loftshool#9]
Нужно добавить валидацию чисел.
(проверить, являются ли они `int` или `float`)
При ошибке выбрасывать ошибку через `trigger_error`

Так же добавить проверку, что деление происходит не на `0`
Так же выбросить ошибку, если делишь на `0` 
https://github.com/Alfatyhin/loftshool/blob/70e8abb992a95b1d647fe019fe47dbccb2e10641/tasks/week_1/src/functions.php#L20-L49

**Comment by Alfatyhin** [comment]
готово

**Comment by Alfatyhin** [comment]
> Нужно добавить валидацию чисел.
> (проверить, являются ли они `int` или `float`)
> При ошибке выбрасывать ошибку через `trigger_error`
> 
> Так же добавить проверку, что деление происходит не на `0`
> Так же выбросить ошибку, если делишь на `0`
> https://github.com/Alfatyhin/loftshool/blob/70e8abb992a95b1d647fe019fe47dbccb2e10641/tasks/week_1/src/functions.php#L20-L49

готово
